name: NoSpam
options:
  bundleIdPrefix: com.konrad
settings:
  base:
    DEVELOPMENT_TEAM: H7477F644K
targets:
  NoSpam:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: NoSpam
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.konrad.nospam
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
    entitlements:
      path: NoSpam/NoSpam.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.konrad.nospam
    info:
      path: NoSpam/Info.plist
      properties:
        UILaunchScreen: {}
        BGTaskSchedulerPermittedIdentifiers:
          - com.konrad.nospam.refresh
        UIBackgroundModes:
          - fetch
    dependencies:
      - target: NoSpamCallDirectory
        embed: true

  NoSpamCallDirectory:
    type: app-extension
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: NoSpamCallDirectory
      - path: NoSpam/SpamNumberStore.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.konrad.nospam.CallDirectory
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
    entitlements:
      path: NoSpamCallDirectory/NoSpamCallDirectory.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.konrad.nospam
    info:
      path: NoSpamCallDirectory/Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.callkit.call-directory
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).CallDirectoryHandler
